// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeotqlircqmuvhfayrhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lb3RxbGlyY3FtdXZoZmF5cmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzMzNTcsImV4cCI6MjA2OTAwOTM1N30.gQWn_Gy0_5UpKL2OdmOalQK7ORSaQ2OG1d-nkeaA1Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});